name: "Run GUT Tests"
description: "Run GUT tests for a Godot project"
author: "josephbmanley"
inputs:
  containerImage:
    description: "The container to run tests inside of."
    default: "barichello/godot-ci:latest"
  useContainer:
    description: "Boolean value of whether or not to run container."
    default: true
  directory:
    description: "The name directory to run tests in."
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: cpu
  color: yellow